# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

palette:
  grey: "#6c6c6c"
secondary_prompt:
  template: "❯❯ "
  foreground: magenta
  background: transparent
transient_prompt:
  template: "❯ "
  foreground: magenta
  background: transparent
  foreground_templates:
  - "{{ if gt .Code 0 }}red{{ end }}"
  - "{{ if eq .Code 0 }}magenta{{ end }}"
console_title_template: "{{ .Shell }} in {{ .Folder }}"
blocks:
- type: prompt
  alignment: left
  segments:
  - properties:
      style: full
    template: "{{ .Path }}"
    foreground: blue
    background: transparent
    type: path
    style: plain
  - properties:
      branch_icon: ""
      commit_icon: "@"
      fetch_status: true
    template: " {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>"
    foreground: p:grey
    background: transparent
    type: git
    style: plain
  newline: true
- type: rprompt
  overflow: hidden
  segments:
  - properties:
      threshold: 5000
    template: "{{ div .Ms 1000 }}s"
    foreground: yellow
    background: transparent
    type: executiontime
    style: plain
- type: prompt
  alignment: left
  segments:
  - template: ❯
    foreground: magenta
    background: transparent
    type: text
    style: plain
    foreground_templates:
    - "{{ if gt .Code 0 }}red{{ end }}"
    - "{{ if eq .Code 0 }}magenta{{ end }}"
  newline: true
version: 3
final_space: true
