return {
	-- {
	-- 	"github/copilot.vim",
	-- 	-- event = "InsertEnter",
	-- 	cmd = "Copilot",
	-- 	config = function()
	-- 		vim.g.copilot_no_tab_map = true -- Disable default `<Tab>` mapping
	-- 		vim.api.nvim_set_keymap("i", "<C-y>", 'copilot#Accept("<CR>")', { expr = true, silent = true })
	-- 	end
	-- },
	-- {
	-- 	"CopilotC-Nvim/CopilotChat.nvim",
	-- 	cmd = "ToggleCopilotChat",
	-- 	dependencies = {
	-- 		{ "github/copilot.vim" }, -- or zbirenbaum/copilot.lua
	-- 		{ "nvim-lua/plenary.nvim", branch = "master" }, -- for curl, log and async functions
	-- 	},
	-- 	build = "make tiktoken", -- Only on MacOS or Linux
	-- 	opts = {
	-- 		-- See Configuration section for options
	-- 	},
	-- 	keys = function()
	-- 		local copilotChat = require("CopilotChat")
	--
	-- 		return {
	-- 			{ "<leader>ct", function() copilotChat.toggle() end, desc = "Toggle Copilot Chat" }
	-- 		}
	-- 	end,
	-- }
}
